# Generated by Django 4.0.2 on 2022-02-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinosolicitacao',
            options={'verbose_name': 'SecaoOPMCOD'},
        ),
        migrations.RemoveField(
            model_name='solicitacoes',
            name='Usuario',
        ),
    ]
