# Generated by Django 4.0.2 on 2022-02-14 13:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitation', '0002_alter_destinosolicitacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='Responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Policial Responsável'),
        ),
        migrations.CreateModel(
            name='HistoricalSolicitacoes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('PostoGradSolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto / Grad')),
                ('ReSolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Re')),
                ('NomeGuerraSolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Guerra')),
                ('CpfSolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPF')),
                ('FuncaoSolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('CodOpmSolicitante', models.CharField(blank=True, max_length=10, null=True, verbose_name='Opm Cod')),
                ('GrandeComandoSolicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Grande Comando')),
                ('UnidadeSolicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade')),
                ('TituloDaSolicitacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Titulo da Solicitação')),
                ('DataDaSolicitacao', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em:')),
                ('DescricaoDoChamado', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descrição do Chamado')),
                ('ConfirmacaoDeSolicitacao', models.BooleanField(blank=True, default=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('AssuntoDaSolicitacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitation.assuntosolicitacao', verbose_name='Assunto')),
                ('CategoriaDaSolicitacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitation.categoriasolicitacao', verbose_name='Categoria')),
                ('DestinoDaSolicitacao', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitation.destinosolicitacao', verbose_name='Destino')),
                ('Responsavel', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Policial Responsável')),
                ('StatusAtual', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='solicitation.statussolicitacao', verbose_name='Status Atual')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Solicitacoes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
