# Generated by Django 4.0.2 on 2022-02-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0003_solicitacoes_responsavel_historicalsolicitacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='statussolicitacao',
            name='ClassStatus',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Class'),
        ),
    ]
