# Generated by Django 4.0.2 on 2022-02-16 14:57

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitation', '0004_statussolicitacao_classstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RespostaDaSolicitacao', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descrição do Chamado')),
                ('RespostaData', models.DateTimeField(auto_now_add=True, null=True)),
                ('RespostaParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply', to='solicitation.respostasolicitacao')),
                ('RespostaResponsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Policial Responsável')),
                ('Solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solicitation.solicitacoes', verbose_name='Chamado')),
            ],
            options={
                'verbose_name': 'RespostaSolicitacao',
                'verbose_name_plural': 'RespostaSolicitacaos',
            },
        ),
    ]
