# Generated by Django 4.0.2 on 2022-02-16 18:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitation', '0005_respostasolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostasolicitacao',
            name='Solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='solicitation.solicitacoes', verbose_name='Chamado'),
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RespostaDoUsuario', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Resposta do Usuário')),
                ('RespostaUsuarioData', models.DateTimeField(auto_now_add=True, null=True)),
                ('RespostaDaSolicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reply', to='solicitation.respostasolicitacao', verbose_name='Chamado')),
                ('RespostaUsuarioResponsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Policial Responsável')),
            ],
            options={
                'verbose_name': 'RespostaDoUsuario',
                'verbose_name_plural': 'RespostaDoUsuarios',
            },
        ),
    ]
