# Generated by Django 4.0.2 on 2022-02-23 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitation', '0006_alter_respostasolicitacao_solicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitacoes',
            name='DataDoEncerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em:'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='DataDoEncerramento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Criado em:'),
        ),
        migrations.AlterField(
            model_name='respostausuario',
            name='RespostaUsuarioResponsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Policial Responsável'),
        ),
    ]
