# Generated by Django 4.0.2 on 2022-03-03 17:02

from django.db import migrations, models
import utils.funcoes_imagens


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0007_historicalsolicitacoes_datadoencerramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitacoes',
            name='DocumentosSolicitacao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='documentos'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='DocumentosSolicitacao',
            field=models.FileField(blank=True, null=True, upload_to=utils.funcoes_imagens.upload_documentos, verbose_name='documentos'),
        ),
    ]
