# Generated by Django 4.0.2 on 2022-03-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0008_historicalsolicitacoes_documentossolicitacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadoBackup',
            fields=[
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('unidade', models.CharField(blank=True, max_length=30, null=True)),
                ('problema', models.CharField(blank=True, max_length=3000, null=True)),
                ('data_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('data_res', models.CharField(blank=True, max_length=50, null=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('PM_res', models.CharField(blank=True, max_length=50, null=True)),
                ('obs', models.CharField(blank=True, max_length=3000, null=True)),
                ('re_ch', models.CharField(blank=True, max_length=9, null=True)),
                ('data_atu', models.CharField(blank=True, max_length=50, null=True)),
                ('PM_atu', models.CharField(blank=True, max_length=50, null=True)),
                ('OPM', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ChamadoBackup',
                'verbose_name_plural': 'ChamadoBackups',
            },
        ),
    ]
