# Generated by Django 4.0.2 on 2022-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0009_chamadobackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadobackup',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamadobackup',
            name='problema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
