# Generated by Django 4.0.2 on 2022-03-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0011_alter_chamadobackup_data_atu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadobackup',
            name='data_atu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
