# Generated by Django 4.0.2 on 2022-03-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0012_alter_chamadobackup_data_atu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadobackup',
            name='data_atu',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
