# Generated by Django 4.0.2 on 2022-03-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0013_alter_chamadobackup_data_atu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assuntosolicitacao',
            options={'verbose_name': 'Assuntos das Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='categoriasolicitacao',
            options={'verbose_name': 'Categorias de Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='chamadobackup',
            options={'verbose_name': 'Chamado Legado Backup', 'verbose_name_plural': 'Chamado Legado Backup'},
        ),
        migrations.AlterModelOptions(
            name='destinosolicitacao',
            options={'verbose_name': 'Destinos das Solicitações'},
        ),
        migrations.AlterModelOptions(
            name='statussolicitacao',
            options={'verbose_name': 'Status das Solicitações'},
        ),
    ]
