# Generated by Django 4.0.2 on 2022-03-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0018_respostasprontas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RespostasProntas',
        ),
    ]
