# Generated by Django 4.0.2 on 2022-03-23 13:03

from django.db import migrations, models
import utils.funcoes_imagens


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0019_delete_respostasprontas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respostasolicitacao',
            name='RespostaParent',
        ),
        migrations.AddField(
            model_name='respostasolicitacao',
            name='RespostaAnexo',
            field=models.FileField(blank=True, null=True, upload_to=utils.funcoes_imagens.upload_documentos_resposta, verbose_name='documentos'),
        ),
    ]
