# Generated by Django 4.0.2 on 2022-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitation', '0020_remove_respostasolicitacao_respostaparent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolicitacoes',
            name='DepartamentoSolicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='historicalsolicitacoes',
            name='DivisaoSolicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='historicalsolicitacoes',
            name='SecaoSolicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='DepartamentoSolicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='DivisaoSolicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='SecaoSolicitante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidade'),
        ),
    ]
