# Generated by Django 4.0.2 on 2022-02-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDeGuerra', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome de Guerra')),
                ('CpfDoUsuario', models.CharField(blank=True, db_index=True, max_length=11, null=True, verbose_name='CPF')),
                ('PostoGraduacao', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome de Guerra')),
                ('ReUsuario', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome de Guerra')),
                ('OpmCod', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de OPM')),
                ('OpmCod1', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de OPM1')),
                ('OpmCod2', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de OPM2')),
                ('OpmCod3', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de OPM3')),
                ('OpmCod4', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de OPM4')),
                ('DataDoLogin', models.DateTimeField(auto_now_add=True, verbose_name='Login em:')),
                ('IpDoUsuario', models.CharField(blank=True, max_length=60, null=True, verbose_name='IP do Usuário')),
            ],
        ),
    ]
