# Generated by Django 4.0.2 on 2022-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginaudit',
            name='OpmCod5',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Código de OPM5'),
        ),
    ]
