# Generated by Django 4.0.2 on 2022-03-07 20:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescricaoCategoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='DescricaoCategoria')),
                ('SlugCategoria', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug categoria')),
                ('Ativo', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescricaoTipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descricao do Tipo')),
                ('SlugTipo', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug Tipo de Ajuda')),
                ('Ativo', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ajuda',
                'verbose_name_plural': 'Tipo de Ajuda',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TituloBlog', models.CharField(blank=True, max_length=50, null=True, verbose_name='Titulo')),
                ('AssuntoBlog', models.CharField(blank=True, max_length=50, null=True, verbose_name='Assunto')),
                ('DescricaoBlog', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Descrição Blog')),
                ('SlugBlog', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug Blog')),
                ('Ativo', models.BooleanField(blank=True, default=True, null=True)),
                ('DataCriacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em:')),
                ('AutorBlog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('CategoriaBlog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CategoriaBlog', to='help_pages.categorias', verbose_name='Categoria')),
                ('LikesBlog', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('TipoBlog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='TipoBlog', to='help_pages.tipo', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Chamado Blog',
                'verbose_name_plural': 'Chamado Blog',
            },
        ),
    ]
