# Generated by Django 4.0.2 on 2022-03-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamadoblog',
            name='TipoBlog',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
