# Generated by Django 4.0.2 on 2022-03-08 01:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('help_pages', '0002_remove_chamadoblog_tipoblog_delete_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='TipoBlog',
            field=models.CharField(choices=[(1, 'PERGUNTAS-FREQUENTES'), (2, 'MODELOS-DE-CHAMADO'), (3, 'TUTORIAIS')], default=1, max_length=3, verbose_name='Tipo do Blog'),
        ),
        migrations.AddField(
            model_name='chamadoblog',
            name='TagsBlog',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='DescricaoCategoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descricao da Categoria'),
        ),
    ]
