# Generated by Django 4.0.2 on 2022-03-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0003_categorias_tipoblog_chamadoblog_tagsblog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='TipoBlog',
            field=models.PositiveIntegerField(choices=[(1, 'PERGUNTAS-FREQUENTES'), (2, 'MODELOS-DE-CHAMADO'), (3, 'TUTORIAIS')], default=1, verbose_name='Tipo do Blog'),
        ),
    ]
