# Generated by Django 4.0.2 on 2022-03-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0005_tipoblog_alter_categorias_tipoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoblog',
            name='ViewCount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Visualizações'),
        ),
    ]
