# Generated by Django 4.0.2 on 2022-03-16 17:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0006_chamadoblog_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadoblog',
            name='IntroducaoBlog',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Introducção do Blog'),
        ),
    ]
