# Generated by Django 4.0.2 on 2022-03-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0007_chamadoblog_introducaoblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamadoblog',
            name='AssuntoBlog',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='chamadoblog',
            name='TituloBlog',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
