# Generated by Django 4.0.2 on 2022-03-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0009_alter_categorias_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='SlugCategoria',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug categoria'),
        ),
    ]
