# Generated by Django 4.0.2 on 2022-03-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0011_chamadoblog_viewconfirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamadoblog',
            name='ViewConfirmation',
        ),
    ]
