# Generated by Django 4.0.2 on 2022-03-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0012_remove_chamadoblog_viewconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='Blog FK')),
                ('User_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='User FK')),
            ],
            options={
                'verbose_name': 'Confirma Visualização',
                'verbose_name_plural': 'Confirma Visualização',
            },
        ),
    ]
