# Generated by Django 4.0.2 on 2022-03-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0014_alter_visualizacaoblog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizacaoblog',
            name='DataVisualizacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
