# Generated by Django 4.0.2 on 2022-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_pages', '0015_visualizacaoblog_datavisualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='Importancia',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
    ]
