# Generated by Django 4.0.2 on 2022-03-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitation', '0014_alter_assuntosolicitacao_options_and_more'),
        ('help_pages', '0005_tipoblog_alter_categorias_tipoblog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoNotificacao', models.IntegerField()),
                ('DataNotificacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('user_has_seen', models.BooleanField(default=False)),
                ('BlogPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='help_pages.chamadoblog')),
                ('DoUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
                ('ParaOUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
                ('RespostaAdmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solicitation.respostasolicitacao')),
                ('RespostaUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solicitation.respostausuario')),
                ('Solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='solicitation.solicitacoes')),
            ],
        ),
    ]
