# Generated by Django 4.0.2 on 2022-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-id',), 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='DataNotificacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em:'),
        ),
    ]
