# Generated by Django 4.0.2 on 2022-03-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='ParaOUsuario',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='DoUsuario',
            new_name='to_user',
        ),
    ]
