# Generated by Django 4.0.2 on 2022-03-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_paraousuario_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_admin',
            field=models.IntegerField(null=True),
        ),
    ]
