# Generated by Django 4.0.2 on 2022-03-16 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0005_tiponotificacao_alter_notification_tiponotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='NovoUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
