# Generated by Django 4.0.3 on 2022-04-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_novouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user_has_archive',
            field=models.BooleanField(default=False),
        ),
    ]
