# Generated by Django 4.0.3 on 2022-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_user_has_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='DataVisualisacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visuzaliada em:'),
        ),
    ]
