# Generated by Django 4.0.3 on 2022-04-09 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_datavisualisacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='DataVisualisacao',
            new_name='DataVisualizacao',
        ),
    ]
